USE [master]
GO

/****** Object:  Database [TrainingTranslate]    Script Date: 23.02.2019 11:39:16 ******/
CREATE DATABASE [TrainingTranslate]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TrainingTranslate', FILENAME = N'A:\Учеба\ADO.NET\HomeWork\ADO.NET_HW2\ADO.NET_HW2\App_Data\TrainingTranslate.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'TrainingTranslate_log', FILENAME = N'A:\Учеба\ADO.NET\HomeWork\ADO.NET_HW2\ADO.NET_HW2\App_Data\TrainingTranslate.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [TrainingTranslate] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TrainingTranslate].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [TrainingTranslate] SET ANSI_NULL_DEFAULT ON 
GO

ALTER DATABASE [TrainingTranslate] SET ANSI_NULLS ON 
GO

ALTER DATABASE [TrainingTranslate] SET ANSI_PADDING ON 
GO

ALTER DATABASE [TrainingTranslate] SET ANSI_WARNINGS ON 
GO

ALTER DATABASE [TrainingTranslate] SET ARITHABORT ON 
GO

ALTER DATABASE [TrainingTranslate] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [TrainingTranslate] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [TrainingTranslate] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [TrainingTranslate] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [TrainingTranslate] SET CURSOR_DEFAULT  LOCAL 
GO

ALTER DATABASE [TrainingTranslate] SET CONCAT_NULL_YIELDS_NULL ON 
GO

ALTER DATABASE [TrainingTranslate] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [TrainingTranslate] SET QUOTED_IDENTIFIER ON 
GO

ALTER DATABASE [TrainingTranslate] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [TrainingTranslate] SET  DISABLE_BROKER 
GO

ALTER DATABASE [TrainingTranslate] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [TrainingTranslate] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [TrainingTranslate] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [TrainingTranslate] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [TrainingTranslate] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [TrainingTranslate] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [TrainingTranslate] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [TrainingTranslate] SET RECOVERY FULL 
GO

ALTER DATABASE [TrainingTranslate] SET  MULTI_USER 
GO

ALTER DATABASE [TrainingTranslate] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [TrainingTranslate] SET DB_CHAINING OFF 
GO

ALTER DATABASE [TrainingTranslate] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [TrainingTranslate] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [TrainingTranslate] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [TrainingTranslate] SET QUERY_STORE = OFF
GO

ALTER DATABASE [TrainingTranslate] SET  READ_WRITE 
GO

